### ISSUE TITLE
Not stable on windows

### ISSUE THREAD

**Issue by obayart** [al6x/nim#1]
Hi,

unfortunately, on windows, the examples stop after a minute or two, with the error message: "NetworkError when attempting to fetch resource".

**Comment by al6x** [comment]
Hi, can you please pos the error message from the nim console?

Also, did you use the latest version? I originally made it with treads but it worked unstable and recently I switched to single-thread version.

**Comment by obayart** [comment]
Hi,

Yes, I use the current version.

I run the examples with: `nim c -r --stackTrace:on twitter.nim`

In fact, the error occurs after about 20-30 seconds. I have the following popup in the: "NetworkError when attempting to fetch resource"

Here is what I have in the console:

C:\Users\Bob\NIM\TWITTER_CLONE\web\examples>nim c -r --stackTrace:on twitter.nim
  http | started on http://localhost:5000
  http | get  / as html started
  http | get  / as html finished, 9ms
[31mE http | /twitter.css file not found[0m
  http | post /edit as json started
  http | post /edit as json finished, 3ms
  http | post /update as json started
  http | post /update as json finished, 4ms
  http | post /add as json started
  http | post /add as json finished, 3ms
  http | post /add as json started
  http | post /add as json finished, 3ms
  http | post /delete as json started
  http | post /delete as json finished, 3ms
  http | post /edit as json started
  http | post /edit as json finished, 4ms
  http | post /add as json started
  http | post /add as json finished, 3ms
  http | post /add as json started
  http | post /add as json finished, 5ms
  http | post /add as json started
  http | post /add as json finished, 2ms
Error: execution of an external program failed: '"C:\Users\Olivier\Desktop\SIDE PROJECT\NIM\TWITTER_CLONE\web\examples\build\twitter.exe" '

Here what I have in the browser console:

error executing 'action' command client.build.js:289:19
    log_in_development http://localhost:5000/assets/client.build.js?hash=1617964422:289
    log http://localhost:5000/assets/client.build.js?hash=1617964422:273
    execute_command http://localhost:5000/assets/client.build.js?hash=1617964422:809
    <anonyme> http://localhost:5000/assets/client.build.js?hash=1617964422:1020
    TEventWrapper http://localhost:5000/assets/client.build.js?hash=1617964422:750
    jQuery 8
    on http://localhost:5000/assets/client.build.js?hash=1617964422:649
    <anonyme> http://localhost:5000/assets/client.build.js?hash=1617964422:1018

Error: NetworkError when attempting to fetch resource. client.build.js:294:17
    log_in_development http://localhost:5000/assets/client.build.js?hash=1617964422:294
    log http://localhost:5000/assets/client.build.js?hash=1617964422:273
    execute_command http://localhost:5000/assets/client.build.js?hash=1617964422:809
    <anonyme> http://localhost:5000/assets/client.build.js?hash=1617964422:1020
    TEventWrapper http://localhost:5000/assets/client.build.js?hash=1617964422:750
    jQuery 8
    on http://localhost:5000/assets/client.build.js?hash=1617964422:649
    <anonyme> http://localhost:5000/assets/client.build.js?hash=1617964422:1018

**Comment by al6x** [comment]
Thanks for the info, the Browser error is just a message saying that it can't talk to the Server.

As for the Server, seems like `twitter.exe` didn't print any stack trace, strange, I don't know what's the problem, maybe some internal Nim error.

P.S.

I also noticed it warned that it can't find the `twitter.css` styles, I use relative paths that seems to be wrong, need to update that.
