### ISSUE TITLE
Cant run nodem rpc example

### ISSUE THREAD

**Issue by gabbhack** [al6x/nim#4]
I tried this one with Nim Compiler Version 1.6.12
https://github.com/al6x/nim/blob/main/nodem/examples/rpc_in_10_lines/server.nim

and got this compile error
```cmd
.nimble\pkgs\nodem-1.4.0\nodem\nexportm.nim(163, 26) Error: undeclared field: 'to_json' for type nodem.Node [type declared in C:\Users\Noname\.nimble\pkgs\nodem-1.4.0\nodem\nodem.nim(12, 6)]
```

**Comment by al6x** [comment]
Thanks for the report, unfortunately don't actively maintain nodem, don't have time.
At the time of its creation I worked on distributed computing project and created it planning to use.
But then I move to other projects and don't need nodem anymore and don't have time to maintain it.

**Comment by al6x** [comment]
It seems like the problem is that I updated shared libraries doing JSON serialisation and didn't updated nodem after that.
